### ISSUE TITLE
[inconveniences] cannot access response "Location" HTTP header

### ISSUE THREAD

**Issue by XSven** [colinnewell/Jenkins-API#21]
- After triggering a build with parameters it is not possible to access the **Location** HTTP header without breaking in the privacy of the Jenkins::API implementation: We accept that _client is a private field! We suggest to implement at least a`response_location_header()` method in addition to the `response_code()` and `response_content()` methods.
- In the event that the `general_call()` method dies the exception message is quite short. From our perspective at least the unexpected response code (`$self->_client->responseCode`) should be part of the exception message.

**Comment by colinnewell** [comment]
I'm currently not able to put too much time into this module, I am however willing to accept pull requests.

Do you have an idea of how to improve the api to allow you to achieve what you want without breaking backwards compatibility?  My one big aim is not to break peoples existing code, but I'm more than happy to have this module improved.

Your ideas generally seem reasonable to me.

If you aren't able to do a pull request I will leave this open and hopefully find some time to implement the suggestions as they do seem like a good idea.

**Comment by XSven** [comment]
I think I can provide a pull request but your project is managed by Dist::Zilla. I have never worked with it before and I am struggling with its installation. I have used the CPAN shell and two different perls (5.14.2, 5.32.1). With perl-5.14.2 even a force notest install does not work. Based on your experience do you have any hints (documentation) that can help me getting Dist::Zilla up and running? Thanks.

**Comment by colinnewell** [comment]
Ah, that's awkward.  What is not using Dist::Zilla stopping you from doing?  I generally use Dist::Zilla so that it's only critical for creating the tarball itself.  For development it ought to be possible to make and test changes without.

For example these should work out of the box without dzill:

```
cpanm --installdeps .
cpanm .
```

Please feel free to submit a PR without worrying about the release issues.  If you really want to get involved in that, that's potentially possible, but this is really my mess so I'm happy to deal if there is code to be released.

Dist::Zilla took a decision early on not to go with the long term backwards compatibility that Perl and a lot of the high profile modules do, and mostly that has reminded me how much I value backwards compatibility.  I love what it allows you to do when you're managing a lot of modules, but if you get off that hamster wheel, it can be painful to update and I end up replacing plugins and updating config a fair bit when I have to deal with occasionally released modules.

**Comment by colinnewell** [comment]
Hmm, after complaining about having to update modules etc. with dzill, it looks like things may well be stable these days.  I managed to spin up an installation and create a tarball easily enough.

If you do really want to see it in action you get it going like this:

```
cpanm Dist::Zilla
dzil authordeps | cpanm
dzil build
```

The one really 'generated' file that's worth interacting with is the `Changes` file and you stick the change info after the $NEXT tag.  Also note that the `README` is generated from the pod of the main module.  

Please do update pod and tests as you make code changes.

**Comment by XSven** [comment]
Ok thanks. I have overlooked the _cpanfile_, so installing the dependencies is not an issue anymore but how do I get a _Makefile_ (ExtUtils::MakeMaker) or a _Build_ file (Module::Build)? How do I trigger a **test** task without having one of these **installers** (Dist::Zilla terminology) available? Sorry for asking these newcomer questions.

**Comment by XSven** [comment]
Maybe CPAN modules are easier to manage these days without having a _Makefile_ or a _Build_ file

`prove -l --verbose t`

does work of course!

**Comment by colinnewell** [comment]
Yes, `prove` should work out of the box.
